archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
  - make tfgen
blobs:
- bucket: dl.briggs.work
  endpoint: https://s3.nl-ams.scw.cloud
  folder: pulumi/releases/plugins/
  region: nl-ams
  ids:
  - archive
  provider: s3
builds:
- binary: pulumi-resource-unifi
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -s
  - -w
  - -X github.com/pulumiverse/pulumi-unifi/provider/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-unifi/
changelog:
  skip: true
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
